services:
  db:
    image: postgres:17.0
    environment:
      POSTGRES_DB: "aisummarizer"
      POSTGRES_USER: "postgre"
      POSTGRES_PASSWORD: "postgre"
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
    ports:
      - "5433:5432"