spring:
  jpa:
    hibernate.ddl-auto: update
  application:
    name: aisummarizer-back
  datasource:
    url: jdbc:postgresql://localhost:5433/aisummarizer
    username: postgre
    password: postgre
server:
  port: 8081
  servlet:
    contextPath: /api/v1